/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReferanslarRouteImport } from './routes/referanslar'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as IndexRouteImport } from './routes/index'

const ReferanslarRoute = ReferanslarRouteImport.update({
  id: '/referanslar',
  path: '/referanslar',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/referanslar': typeof ReferanslarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/referanslar': typeof ReferanslarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/referanslar': typeof ReferanslarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/referanslar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeri'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/referanslar'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/referanslar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HizmetlerRoute: typeof HizmetlerRoute
  IletisimRoute: typeof IletisimRoute
  ReferanslarRoute: typeof ReferanslarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/referanslar': {
      id: '/referanslar'
      path: '/referanslar'
      fullPath: '/referanslar'
      preLoaderRoute: typeof ReferanslarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HizmetlerRoute: HizmetlerRoute,
  IletisimRoute: IletisimRoute,
  ReferanslarRoute: ReferanslarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
